apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gkmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gkmn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0028-app
  name: devfile-sample-gkmn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gkmn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gkmn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-gkmn@sha256:2a66df0e98ee8cab40a16a46667a10c7336f926373a4910c4765475bf747059c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
